import {
  Wifi,
  Car,
  ThermometerSnowflake,
  UtensilsCrossed,
  Waves,
  PawPrint,
  Tv,
  CookingPot,
  Clock,
  Ban,
  CigaretteOff,
  Gift,
  PartyPopper,
  Hotel,
  TreePine,
  Building2,
  Building,
  Tent,
  BedDouble,
  House,
  Landmark,
  Mountain,
  Bike,
} from "lucide-react";

export const ICON_MAP = {
  // Amenities / features
  wifi: Wifi,
  car: Car,
  "thermometer-snowflake": ThermometerSnowflake,
  utensils: UtensilsCrossed,
  water: Waves,
  "paw-print": PawPrint,
  tv: Tv,
  "kitchen-set": CookingPot,
  clock: Clock,
  ban: Ban,
  "smoking-ban": CigaretteOff,
  gift: Gift,
  "party-popper": PartyPopper,
  // Categories
  hotel: Hotel,
  "tree-pine": TreePine,
  "building-2": Building2,
  building: Building,
  tent: Tent,
  "bed-double": BedDouble,
  house: House,
  landmark: Landmark,
  mountain: Mountain,
  bike: Bike,
};
